# Setup
title:               Digital Humanities Practicum
tagline:             'MLL 774 - ENG 613 | University of Miami | Spring 2023'
description:         'DH Practicum Spring 2023'
url:                 http://susannalles.github.io/DHPracticum_Spring23
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Susanna Allés Torrent
  url:               https://twitter.com/sallesto
  email:             susanna_allles@miami.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
