# Setup
title:               Mapping Shakespearean Adaptation in Asia
tagline:             
description:         2023 Digital Humanities Project
url:                 https://austraea.github.io
baseurl:             '/Mapping'
paginate:            5
permalink:           pretty
github.repo:         https://austraea/github.io

# About/contact
author:
  name:              Hyekyung Jung
  url:               
  email:             hxj240@miami.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
